### ISSUE TITLE
sdf2tinkerxyz Error

### ISSUE THREAD

**Issue by gkxiao** [KristapsE/DP4-AI#45]
Dear Developer，

When I use tinker as conformational search engine,  there are some wrong with sdf2tinkerxyz.

The command I used was:
```
PyDP4.py -w m -m t -f mmff ANPN-D-4-60 Carbon_NMR
```

```
==========================
PyDP4 script,
integrating Tinker/MacroModel,
Gaussian/NWChem and DP4
v1.0

Copyright (c) 2015-2019 Kristaps Ermanis, Alexander Howarth, Jonathan M. Goodman
Distributed under MIT license
==========================

Settings read from settings.cfg:
  TinkerPath: /home/cloudam/software/tinker
  GausPath: g16
['ANPN-D-4-60']
Carbon_NMR
NMR_path
/home/cloudam/work/dp4/tinker/Carbon_NMR
Current working directory: /home/cloudam/work/dp4/tinker
Initial input files: ['ANPN-D-4-60']
NMR file: [PosixPath('/home/cloudam/work/dp4/tinker/Carbon_NMR/uxnmr_1.par')]
Workflow: m
Generated input files: ['ANPN-D-4-60']

Assuming all computations are done? ...  False
Using preexisting DFT data? ...  False
Performing conformational search using Tinker

Setting up Tinker files...
/bin/sh: /home/cloudam/software/DP4-AI/sdf2tinkerxyz: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
Traceback (most recent call last):
  File "/home/cloudam/software/DP4-AI/PyDP4.py", line 718, in <module>
    main(settings)
  File "/home/cloudam/software/DP4-AI/PyDP4.py", line 206, in main
    TinkerInputs = Tinker.SetupTinker(settings)
  File "/home/cloudam/software/DP4-AI/Tinker.py", line 56, in SetupTinker
    outp = subprocess.check_output(convinp + inpf + '.sdf', shell=True)
  File "/home/cloudam/rdkit2020/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/cloudam/rdkit2020/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/cloudam/software/DP4-AI/sdf2tinkerxyz -k /home/cloudam/software/DP4-AI/default.key <ANPN-D-4-60.sdf' returned non-zero exit status 126.
(/home/cloudam/rdkit2020) [cloudam@master tinker]$ /home/cloudam/software/DP4-AI/sdf2tinkerxyz -k /home/cloudam/software/DP4-AI/default.key <ANPN-D-4-60.sdf
-bash: /home/cloudam/software/DP4-AI/sdf2tinkerxyz: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
```
And then I type：
```
sdf2tinkerxyz -k /home/cloudam/software/DP4-AI/default.key <ANPN-D-4-60.sdf
```
```
-bash: /home/cloudam/software/DP4-AI/sdf2tinkerxyz: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
```
How can I fix it?

Thank you very much,

Gaokeng Xiao

**Comment by gkxiao** [comment]
Solved it.  Replace the  sdf2tinkerxyz with new one complied by myself. The source code: http://sdf2xyz2sdf.sourceforge.net
